pipeline {
    agent any

    stages {
        stage('Build') {
            parallel {
                stage('Build: api') {
                    steps {
                        sh "sudo docker build -f ${WORKSPACE}/AppCode/Dockerfile.python ${WORKSPACE}/AppCode/api/"
                    }
                }
                stage('Build: redis') {
                    steps {
                        sh "sudo docker build -f ${WORKSPACE}/AppCode/Dockerfile.python ${WORKSPACE}/AppCode/redis/"
                    }
                }
                stage('Build: worker') {
                    steps {
                        sh "sudo docker build -f ${WORKSPACE}/AppCode/Dockerfile.python ${WORKSPACE}/AppCode/worker/"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}