pipeline {
    agent any

    stages {
        stage('Build') {
            parallel {
                stage('Build: api') {
                    steps {
                        docker build -f ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/Dockerfile.python ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/api/
                    }
                }
                stage('Build: redis') {
                    steps {
                        docker build -f ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/Dockerfile.python ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/redis/
                    }
                }
                stage('Build: worker') {
                    steps {
                        docker build -f ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/Dockerfile.python ${WORKSPACE}/istea_examen_docker_resuelto/AppCode/worker/
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}